answers = (1, 2, 3, 2, 1, 2, 1, 3, 1, 2, 1, 2, 3, 3, 2, 1, 2, 1, 2, 1)
user_answer = []
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
user_answer.append(int(input()))
if tuple(user_answer) == answers:
    print('Экзамен сдан')
else:
    print('Экзамен провален')
